apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: film-storage-service-mesh-canary
  namespace: user14-gitops-argocd
spec:
  destination:
    namespace: user14-canary-service-mesh
    server: 'https://kubernetes.default.svc'
  source:
    path: rhsm-canary
    repoURL: https://github.com/deepeess/workshop-argo-rollouts-resources.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - edit.values.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true