apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: film-storage-canary
  namespace: user14-gitops-argocd
spec:
  destination:
    namespace: user14-canary
    server: 'https://kubernetes.default.svc'
  source:
    path: canary
    repoURL: https://github.com/deepeess/workshop-argo-rollouts-resources.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true